services:
  client:
    image: node:16.15
    working_dir: /app
    volumes:
      - ./lib/client/app:/app
    ports:
      - 8888:4200
    command: npm start
  cognito:
    image: jagregory/cognito-local
    ports:
      - 9229:9229
    volumes:
      - .cognito:/app/.cognito
