services:
  web-client:
    image: daily-tracker-client-image
    ports:
      - 8888:80
  cognito:
    image: jagregory/cognito-local
    ports:
      - 9229:9229
    volumes:
      - .cognito:/app/.cognito
